run: true
n_jobs: 16
filter_data: true # true: enables the descriptor filtering step. 
                  # false: molecules are not filtered by either borders or structural_constraints

structural_constraints:
  enabled: false
  type_limits:
    ".=O": 4
    C2r: 6
    C3r: 6
    Car: 12
    Cs2: 6
    Cs3: 8
    Csp: 2
    Nac: 3
    Nd+: 1
    Nd0: 2
    O_a: 4
    O_d: 2
    SO2: 1
    Sul: 1
    Hal: 3
  element_limits:
    N: 6
    O: 4
    S: 1
  max_n_or_o_atoms: 10
  max_small_rings_3_4: 0
  max_acyclic_chain_length: 4

# Generic pooled profile calibrated on molecules from ZINK-250k and ChEMBL 34 
borders:
  n_atoms_min: 19
  n_atoms_max: 81
  n_heavy_atoms_min: 11
  n_heavy_atoms_max: 43
  n_het_atoms_min: 1
  n_het_atoms_max: 14
  n_N_atoms_min: 0
  n_N_atoms_max: 9
  fN_atoms_min: 0
  fN_atoms_max: 0.334
  fNS_atoms_min: 0
  fNS_atoms_max: 0.364
  molWt_min: 164
  molWt_max: 603
  logP_min: -2.2
  logP_max: 5.5
  sw_min: -25.6
  sw_max: 0.0
  ring_size_min: 3
  ring_size_max: 7
  n_rings_min: 0
  n_rings_max: 7
  n_aroma_rings_min: 0
  n_aroma_rings_max: 5
  n_fused_aromatic_rings_min: 0
  n_fused_aromatic_rings_max: 2
  n_rigid_bonds_min: 8
  n_rigid_bonds_max: 41
  n_rot_bonds_min: 0
  n_rot_bonds_max: 10
  hbd_min: 0
  hbd_max: 5
  hba_min: 0
  hba_max: 11
  fsp3_min: 0
  fsp3_max: 1
  # has_spider_side_chains_min: 0
  # has_spider_side_chains_max: 0
  # fraction_ring_system_min: 0.25
  # fraction_ring_system_max: 1
  mce18_min: 4
  mce18_max: 144
  tpsa_min: 7
  tpsa_max: 183
  qed_min: 0.17
  qed_max: 0.942
filtered_cols_to_plot:
- n_atoms
- n_heavy_atoms
- n_het_atoms
- n_N_atoms
- n_O_atoms
- n_S_atoms
- n_NO_atoms
- fN_atoms
- fNS_atoms
- n_small_rings_3_4
- max_acyclic_chain_length
- has_spider_side_chains
- fraction_ring_system
- ".=O"
- C2r
- C3r
- Car
- Cs2
- Cs3
- Csp
- Nac
- Nd+
- Nd0
- O_a
- O_d
- SO2
- Sul
- Hal
- molWt
- logP
- sw
- ring_size
- n_rings
- n_aroma_rings
- n_fused_aromatic_rings
- n_rigid_bonds
- n_rot_bonds
- hbd
- hba
- fsp3
- mce18
- tpsa
- qed
discrete_features_to_plot:
- n_het_atoms
- n_N_atoms
- n_O_atoms
- n_S_atoms
- n_NO_atoms
- ring_size
- n_rings
- n_aroma_rings
- n_small_rings_3_4
- max_acyclic_chain_length
- has_spider_side_chains
- ".=O"
- C2r
- C3r
- Car
- Cs2
- Cs3
- Csp
- Nac
- Nd+
- Nd0
- O_a
- O_d
- SO2
- Sul
- Hal
- n_fused_aromatic_rings
- n_rigid_bonds
- n_rot_bonds
- hbd
- hba
